### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by wolvre** [utwente-fmt/ltsmin#71]
Any idea about the exception below?

$ spins -o3 tsr_4x3.pml 
Exception in thread "main" java.lang.UnsupportedClassVersionError: spins/Compile : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Compilation of tsr_4x3.pml failed

**Comment by wolvre** [comment]
Linux 2.6.32-431.20.5.el6.x86_64
Java 1.7.0_65

**Comment by Meijuh** [comment]
Doesn't look like an LTSmin issue, can you show the output of `javac -version` and `java -version`? They should both show the same version#.

**Comment by wolvre** [comment]
I tried this. Both are same: 1.7.0_65

**Comment by Meijuh** [comment]
Maybe ant uses a different javac executable on your machine? What does `locate javac` or `find / -type f -name javac` say?

**Comment by wolvre** [comment]
Thanks a lot! 

I guess this is because spins.jar, included in the src of ltlmin-2.1, is created by java 1.8, while I have only java 1.7 installed in my machine. Anyway to get java-1.7-compatble spins?

**Comment by Meijuh** [comment]
Ah, I hadn't considered this. I think it is indeed better to release LTSmin/spins with Java 7. You could compile spins yourself, checkout the master branch at `https://github.com/utwente-fmt/spins/tree/master`. `CD` into src and run `ant`. Then, `cd ..` and you can run spins.sh with `bash`. 

If you plan on model checking with LTSmin just provide the compiled file: `tsr_4x3.pml.spins` to prom2lts-*, produced with the latter method. `prom2lts-*` accepts both Promela source files and compiled files.

**Comment by Meijuh** [comment]
I will leave this open, so that we will use Java 7 for the next LTSmin release.

**Comment by Meijuh** [comment]
A better solution is of course not to include a compiled jar file in a source release tarball.

**Comment by alaarman** [comment]
There is no good solution as the different Java VMs are incompatible.
If you do not include the tarball, users are dependent on a JavaSDK instead of the _right_ JavaRE.
Perhaps, we should specify the Java version as a SpinS dependency?

**Comment by Meijuh** [comment]
If we release a source tarball, why should we also let the user compile SpinS with the JAVAJDK?

**Comment by alaarman** [comment]
I am proposing to include the tarball in LTSmin.
If the tarball is compiled for maximum compatibility this should solve the problem. You can give javac command line options to target earlier VM versions.

**Comment by Meijuh** [comment]
I am closing this issue, since it is quite old.
